# .air.toml

# The root directory where Air will look for files to watch.
root = "."
# The directory where the compiled binary will be placed.
bin = "build/linux"

# The main Go file to run.
main = "main.go"

# List of file extensions to watch.
# Leave empty to watch all files.
watch_ext = ["go","html","yaml"]

# List of file paths to ignore.
ignore = [
    "logs/*",
    "vendor/*",
    "build/*"
]

# The command to run when changes are detected.
# If empty, the default "go build" will be used.
build = "go build -o build/linux/HTMX_GO main.go"

# The command to run after a successful build.
# This should be the command to run your application.
cmd = ".build/linux/HTMX_GO"

# Optionally, set a delay between changes before restarting.
delay = "100ms"
